name: Docker Image Publish

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
    - name: Build & Push to Docker Hub
      # You may pin to the exact commit or the version.
      uses: opspresso/action-docker@master
      with:
          args: --docker
      env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          TAG_NAME: "v0.1.14"
          BUILDX: "true"
          IMAGE_NAME: "keitarodxs/aia-utils"
          
